### PR TITLE
Fix Aspell output parsing when the original words contains a colon

### LINKED ISSUE #24: Aspell output parsing for Swedish
Hello, 

I encounter an error while parsing the output of Aspell for Swedish sentences with words containing a colon (`:`) - in Swedish and Finnish, words can contain colons, see https://en.wikipedia.org/w/index.php?title=Colon_(punctuation)

here is the output of aspell:
```console
$ aspell --lang=sv --encoding=UTF-8 -a
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.7-20110707)
S:t Petersburg är i Ryssland
& S:t 23 0: St, Set, Sot, Söt, Stl, Stå, Sy, Ät, Åt, Est, Ost, Öst, SI, SM, TT, Sa, Se, Sk, So, Så, Ut, Yt, SJ
? Petersburg 0 4: Peters
*
*
*
```

The issue comes from [here](https://github.com/mekras/php-speller/blob/dc54570fcc32450457eed0b94046a8d847712110/src/Ispell/Ispell.php#L186:): as there is more than one colon in the line, the `$parts` contains more than 2 elements, and at line 192, `$parts[0][3]` is not set, resulting in a notice, and even a fatal error if strict_types is enabled (`PHP Fatal error:  Uncaught TypeError: trim() expects parameter 1 to be string, null given`).

I guess a regexp would be more suitable in this case, I can try to do a PR if needed (though I'm not sure how to implement the tests yet...)

### PR DESCRIPTION
**Pull request by mmetayer**
Fixes #24

### CODE REVIEW

File: src/Ispell/Ispell.php [hunk 1]
```diff
@@ -183,15 +183,16 @@ protected function parseOutput(string $output): array
...
-                    $parts[1] = explode(', ', trim($parts[1]));
-                    $word = $parts[0][1];
-                    $issue = new Issue($word);
-                    $issue->line = $lineNo;
-                    $issue->offset = trim($parts[0][3]);
-                    $issue->suggestions = $parts[1];
-                    $issues [] = $issue;
+                    $matches = [];
+                    $pattern = '/^& (?<original>[^\s]+) \d+ (?<offset>\d+): (?<suggestions>.*)$/';
+                    if (1 === preg_match($pattern, $line, $matches)) {
```
Comment (mmetayer) [inline src/Ispell/Ispell.php:188]: Not sure what to do if it _doesn't_ match the pattern :thinking:

Comment (icanhazstring) [reply src/Ispell/Ispell.php:188]: If it's not matching, previously we wouldn't have anything in `$parts`. So that would be an empty array.
I would say the line is simply ignored.

But you could write a test for that where the Ispell output doesn't match. And see if it breaks :)

File: tests/Unit/Aspell/AspellTest.php [hunk 2]
```diff
@@ -115,4 +115,35 @@ public function testCheckText(): void
...
+
+    /**
+     * Test spell checking when a word contains a colon
+     *
+     * @see https://github.com/mekras/php-speller/issues/24
+     */
+    public function testCheckTestWithColon(): void
+    {
+        $source = $this->prophesize(EncodingAwareSource::class);
+        $source->getEncoding()->shouldBeCalled()->willReturn('UTF-8');
```
Comment (icanhazstring) [inline tests/Unit/Aspell/AspellTest.php]: You don't need to add `shouldBeCalled()` to every method your are mocking.
It is not necessary here because the only thing you want to provide is the `string` value.

What you could have also done is using a instance of `StringSource`
E.g.

```php
$source = new StringSource('S:t Petersburg är i Ryssland');
```

Because this is simply a "DataObject" which doesn't need mocking.

**Review by icanhazstring — CHANGES_REQUESTED** [review]
Create fix. Thank you!
What you could add is a test to be expected to fail if the "return" value from ispell output does not match your regex.

Other than that. Create PR!

**Review by icanhazstring — APPROVED** [review]

**Comment by icanhazstring** [comment]
Nice. Thanks for the fix 👍

**Comment by icanhazstring** [comment]
Tagged with 2.1.1. Thanks again 👏 
https://github.com/mekras/php-speller/releases/tag/2.1.1
